config/routes.rb
Rails.application.routes.draw do
  root to: 'items#home'
  get 'items/map', to: 'items#map', as: :map
  get 'items/search', to: 'items#search', as: :search
  get 'items/presentation', to: 'items#presentation', as: :presentation

  mount ActionCable.server, at: '/cable'

  resources :items, except: :home do
    get 'edit_lost', to: 'items#edit_lost', as: :edit_lost
    get 'edit_found', to: 'items#edit_found', as: :edit_found
    member do
      patch :solved
    end
    collection do
      get 'lost'
      get 'found'
      get 'new_lost'
      get 'new_found'
    end
    resources :conversations, only: [:create, :new]
  end

  resources :conversations, only: [:index, :show, :destroy] do
    resources :messages, only: [:index, :new, :create]
  end

  devise_for :users
   resources :users, only: [:show] do
    resources :reviews, only: [:new, :create, :index]
    end
    resources :reviews, only: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :keeper, class_name: 'User', foreign_key: :keeper_id
  belongs_to :seeker, class_name: 'User', foreign_key: :seeker_id
  belongs_to :item
  has_many :messages, dependent: :destroy

  #validates
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :find_item, only: %i[new create]

  def new
    @message = Message.new
    # need to pass a new message
    # nested in items
  end

  def create
    @conversation = Conversation.create(
      item: @item,
      seeker: current_user,
      keeper: @item.user
    )

    @message = Message.new(conversation_params)
    @message.conversation = @conversation
    @message.user = current_user
    @message.save

    broadcast_message

    redirect_to @conversation
  end

  def destroy
  @conversation = current_user.conversations.find(params[:id])

  @conversation.destroy
    if @conversation.destroy
      flash[:notice] = "Conversation has been deleted!"
      redirect_to conversations_path
    else
      render :index
    end
  end


  def show
    @conversation = current_user.conversations.includes(messages: [:user, :photo_attachment]).where(id: params[:id]).first
    raise ActiveRecord::RecordNotFound unless @conversation.present?
  end


  def index
    @conversations = current_user.conversations.includes(:messages).order('messages.created_at desc')
  end

  private


  def broadcast_message
    ActionCable.server.broadcast(
      "user_#{@conversation.item.user_id}",
      user: current_user.id,
      conversation: @conversation.id,
      notification: render_to_string(partial: 'shared/new_message', locals: { message: @message })
    )
  end

  def find_item
    @item = Item.find(params[:item_id])
  end

  def conversation_params
    params.require(:message).permit(:content, :photo)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def other_party(conversation)
    user = (current_user == conversation.keeper) ? conversation.seeker : conversation.keeper

    user.first_name
  end
end

app/views/conversations/index.html.erb
<div class="show-page-wrap">
  <div class="show-container-list">
    <h2><span class="green">Your messages</span></h2>
    <% if @conversations.any? %>
      <% @conversations.each do |conversation| %>
        <div class="messages-list-card">
          <h5>
            <%= link_to other_party(conversation), conversation %>
          </h5>

          <div class="messages-list-details">
            <div class="messages-list-messages">
              <%= link_to conversation.messages.first.content, conversation %>
            </div>
            <div class="messages-list-time">
              <%= distance_of_time_in_words(conversation.messages.first.created_at, Time.now, options = {}) %> ago
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="sorry-message"><h5>Your inbox is empty</h5></div>
    <% end %>
  </div>
</div>

app/views/conversations/new.html.erb
<div class="show-page-wrap">
  <div class="message-container">
    <div class="message-window">

    </div>


    <div class="message-form">
      <%= simple_form_for :message, url: item_conversations_path(@item) do |f| %>

        <label for="message_photo" class="image-upload"></label>
        <%= f.input :photo, as: :file, label: false, input_html: { class: 'd-none' } %>

        <%= f.input :current_user, as: :hidden, input_html: { value: current_user.id } %>
        <%= f.input :content, input_html: { placeholder: 'Write message...', autocomplete: 'off' } %>
        <div class="loader d-none">
          <%= render 'shared/loader' %>
        </div>
        <%= f.button :submit, "", id: "message-new-button" %>
      <% end %>
    </div>

  </div>
</div>

app/views/conversations/show.html.erb
<div class="show-page-wrap" id="conversation">
  <div class="message-container">
    <div class="message-window d-none" data-id="<%= @conversation.id %>">
      <%= render @conversation.messages %>
    </div>
  </div>
</div>

<div class="message-form">
  <%= simple_form_for [@conversation, Message.new], remote: true do |f| %>
    <label for="message_photo" class="image-upload"></label>
    <%= f.input :photo, as: :file, label: false, input_html: { class: 'd-none' } %>

    <%= f.input :current_user, as: :hidden, input_html: { value: current_user.id } %>
    <%= f.input :content, input_html: { placeholder: 'Write message...', autocomplete: 'off', autofocus: true } %>
      <div class="loader d-none">
        <%= render 'shared/loader' %>
      </div>
    <%= f.button :submit, "", id: "message-new-button", class: 'button-none' %>
  <% end %>
</div>