config/routes.rb
Rails.application.routes.draw do
  root to: 'items#home'
  get 'items/map', to: 'items#map', as: :map
  get 'items/search', to: 'items#search', as: :search
  get 'items/presentation', to: 'items#presentation', as: :presentation

  mount ActionCable.server, at: '/cable'

  resources :items, except: :home do
    get 'edit_lost', to: 'items#edit_lost', as: :edit_lost
    get 'edit_found', to: 'items#edit_found', as: :edit_found
    member do
      patch :solved
    end
    collection do
      get 'lost'
      get 'found'
      get 'new_lost'
      get 'new_found'
    end
    resources :conversations, only: [:create, :new]
  end

  resources :conversations, only: [:index, :show, :destroy] do
    resources :messages, only: [:index, :new, :create]
  end

  devise_for :users
   resources :users, only: [:show] do
    resources :reviews, only: [:new, :create, :index]
    end
    resources :reviews, only: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_loader.html.erb
<div class="loadingio-spinner-ellipsis-uywstdsw6d"><div class="ldio-mnx3hawpnm">
<div></div><div></div><div></div><div></div><div></div>
</div></div>
<style type="text/css">
@keyframes ldio-mnx3hawpnm {
   0% { transform: translate(15.4px,67.76px) scale(0); }
  25% { transform: translate(15.4px,67.76px) scale(0); }
  50% { transform: translate(15.4px,67.76px) scale(1); }
  75% { transform: translate(67.76px,67.76px) scale(1); }
 100% { transform: translate(120.12px,67.76px) scale(1); }
}
@keyframes ldio-mnx3hawpnm-r {
   0% { transform: translate(120.12px,67.76px) scale(1): }
 100% { transform: translate(120.12px,67.76px) scale(0); }
}
@keyframes ldio-mnx3hawpnm-c {
   0% { background: #67d6ba }
  25% { background: #67d6ba }
  50% { background: #67d6ba }
  75% { background: #67d6ba }
 100% { background: #67d6ba }
}
.ldio-mnx3hawpnm div {
  position: absolute;
  width: 7px;
  height: 7px;
  border-radius: 50%;
  transform: translate(20px,67.76px) scale(1);
  background: #67d6ba;
  animation: ldio-mnx3hawpnm 3.4482758620689657s infinite cubic-bezier(0,0.5,0.5,1);
}
.ldio-mnx3hawpnm div:nth-child(1) {
  background: #67d6ba;
  transform: translate(120.12px,67.76px) scale(1);
  animation: ldio-mnx3hawpnm-r 0.8620689655172414s infinite cubic-bezier(0,0.5,0.5,1), ldio-mnx3hawpnm-c 3.4482758620689657s infinite step-start;
}.ldio-mnx3hawpnm div:nth-child(2) {
  animation-delay: -0.8620689655172414s;
  background: #67d6ba;
}.ldio-mnx3hawpnm div:nth-child(3) {
  animation-delay: -1.7241379310344829s;
  background: #67d6ba;
}.ldio-mnx3hawpnm div:nth-child(4) {
  animation-delay: -2.586206896551724s;
  background: #67d6ba;
}.ldio-mnx3hawpnm div:nth-child(5) {
  animation-delay: -3.4482758620689657s;
  background: #67d6ba;
}
.loadingio-spinner-ellipsis-uywstdsw6d {
  width: 154px;
  height: 154px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-mnx3hawpnm {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-mnx3hawpnm div { width: flex-grow; }
/* generated by https://loading.io/ */
</style>

app/views/shared/_menu.html.erb
<% if params[:action] == 'new_found' || params[:action] == 'new_lost' || (params[:action] == 'new' && params[:controller] == 'items') %>

<% elsif params[:action] == 'lost' || params[:action] == 'map' %>

  <div class="top-menu-wrap">
    <div class="menu-item">
        <%= image_tag 'settings_white.svg', class: 'menu-settings' %>
    </div>
    <div class="menu-item">
        <%= link_to image_tag("logo_green.svg", class: "menu-logo"), root_path %>
    </div>
    <div class="menu-item">
      <%= link_to image_tag('chat_white.svg', class: 'menu-chat'), conversations_path %>
    </div>
  </div>

<% elsif params[:action] == 'show' && params[:controller] == 'items' && @item.lost? %>

  <div class="top-menu-wrap-dark">
    <div class="menu-item">
        <%= image_tag 'settings_white.svg', class: 'menu-settings' %>
    </div>
    <div class="menu-item">
        <%= link_to image_tag("logo_green.svg", class: "menu-logo"), root_path %>
    </div>
    <div class="menu-item">
      <%= link_to image_tag('chat_white.svg', class: 'menu-chat'), conversations_path %>
    </div>
  </div>

<% elsif (params[:action] == 'show' || params[:action] == 'new') && params[:controller] == 'conversations' %>

  <div class="top-menu-wrap-white">
    <div class="menu-item">
        <%=link_to image_tag('simple_arrow_black.svg', class: 'menu-back'), :back %>
    </div>
    <div class="menu-item menu-message-user">
      <i class="fas fa-user"></i>
      <% if params[:action] == 'show' %>
        <% if current_user == @conversation.keeper %>
          <%= link_to (@conversation.seeker.first_name), user_path(@conversation.seeker.id)  %>
        <% else %>
          <%= link_to (@conversation.keeper.first_name), user_path(@conversation.keeper.id)  %>
        <% end %>
      <% end %>
    </div>
    <div class="menu-item">
        <%= link_to image_tag('chat_black.svg', class: 'menu-chat'), conversations_path%>
    </div>
  </div>

<% else %>

  <div class="top-menu-wrap-white">
    <div class="menu-item">
      <% if params[:controller] == 'users' %>
        <%=link_to image_tag('simple_arrow_black.svg', class: 'menu-back'), :back %>
      <% else %>
        <%= image_tag 'settings_black.svg', class: 'menu-settings' %>
      <% end %>

    </div>
    <div class="menu-item">
      <%= link_to image_tag("logo_green.svg", class: "menu-logo"), root_path %>
    </div>
    <div class="menu-item">
        <%= link_to image_tag('chat_black.svg', class: 'menu-chat'), conversations_path %>
    </div>
  </div>

<% end %>


<% if params[:action] == 'new_found' || (params[:action] == 'new' && params[:controller] == 'items') %>

<% else %>
  <div class="menu-wrap">

    <div class="menu-item item-left">
        <%= link_to image_tag("map_black.svg", class: "menu-map"), map_path, alt: 'Submit'%>
      </form>
    </div>

    <div class="menu-item">
      <%= link_to 'LOST', lost_items_path%>
<!--       <input type="hidden" id="latitude" name="latitude" value="">
      <input type="hidden" id="longitude" name="longitude" value=""> -->
    </div>

    <div class="menu-item">
      <div class="menu-button">
        <%= image_tag 'plus_white.svg', class: 'menu-plus' %>
      </div>
    </div>

    <div class="menu-item">
      <%= link_to 'FIND', found_items_path%>
    </div>

    <div class="menu-item item-right">
      <%= link_to (image_tag 'search_black.svg', class: 'menu-search'),  search_path %>
    </div>
  </div>

  <div class="menu-background-dark">
  </div>

  <div class="menu-title-hidden">
    <h2>Add a new Item</h2>
  </div>

  <div class="menu-background-green">
    <%= link_to 'Lost?', new_lost_items_path(state: :lost), class: 'button-lost-menu' %>
    <%= link_to 'Found?', new_found_items_path(state: :found), class: 'button-found-menu' %>

    <div class="menu-wrap-green">
        <div class="menu-button-back">
        <%= image_tag 'arrow_green.svg', class: 'menu-plus' %>
      </div>
    </div>
  </div>

<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_new_message.html.erb
<%= link_to conversation_path(message.conversation) do %>
  <div class="message-notification-wrap">
    <%= image_tag 'chat_green.svg', class: 'new_message-image' %>
    <div class="notification-details">
      <div class="notification-user">
        New message from <%= message.user.first_name %>
      </div>
      <div class="notification-message">
        <%= truncate(message.content, length: 100) %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_show_card.html.erb
<% if params[:action] == 'lost' %>

  <% items.each do |item| %>
    <%= link_to item_path(item) do %>
      <div class="show-card lost">
        <div class="show-card-content lost">
          <h5><%= item.title %></h5>
          <div class="show-drescription lost">
             <%= item.description %>
          </div>
        </div>

        <div class="show-card-distance">
          <div class="show-card-map">
            <%= image_tag 'map_green.svg', class: 'show-map-pointer' %>
          </div>
          <div class="show-distance">
            <%= number_to_human(item.distance_from(location) * 1000, units: {unit: "m", thousand: "km"}) %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

<% else %>

  <% items.each do |item| %>
    <%= link_to item_path(item) do %>
      <div class="show-card">
        <div class="show-card-content">
          <h5><%= item.title %></h5>
          <div class="show-drescription">
             <%= item.description %>
          </div>
        </div>

        <div class="show-card-distance">
          <div class="show-card-map">
            <%= image_tag 'map_green.svg', class: 'show-map-pointer' %>
            </div>
          <div class="show-distance">
             <%= number_to_human(item.distance_from(location) * 1000, units: {unit: "m", thousand: "km"}) %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_slider.htm.erb
  <div class="container-slider">
  <div class="slider-container">
    <div class="track">
      <div class="progress"></div>
      </div>
     <div class="thumb">
       <div class="thumb-indicator"></div>
    </div>
  </div>
  </div>

app/views/shared/_user_settings.html.erb
<div class="settings-page-wrap">

  <div class="top-menu-wrap">
    <div class="menu-item">
        <%= image_tag 'simple_arrow_white.svg', class: 'settings-back' %>
    </div>
    <div class="menu-item">
        <%= link_to image_tag("logo_green.svg", class: "menu-logo"), root_path %>
    </div>
    <div class="menu-item">
      <%= link_to image_tag('chat_white.svg', class: 'menu-chat'), conversations_path %>
    </div>
  </div>

  <% if user_signed_in? %>

    <div class="settings-wrap">

      <!-- profile picture and name -->

      <div class="settings-user-wrap">
        <%= image_tag 'placeholder.jpg', class: 'settings-placeholder' %>
        <div class="settings-user-details">
          <h4><%= current_user.first_name %></h4>
          <h4> <%= current_user.last_name %></h4>
          <div class="settings-average-review">
            <%= render 'reviews/rating_settings', user_rating: current_user.average_rating %>
          </div>
          <p>Add profile picture</p>
        </div>
      </div>

      <!-- Account information -->

      <div class="settings-account">
        <div class="account-items account-header">
          Account settings
          <%= link_to 'Edit profile', edit_user_registration_path, class: 'settings-links' %>
        </div>
        <div class="account-items">
          <p>Email</p>
          <p><%= current_user.email %></p>
        </div>
        <div class="account-items">
          <p>Phone number</p>
          <p><%= current_user.phone_number %></p>
        </div>
      </div>

      <!-- Display lost and found items -->

      <% if current_user.items.lost %>

        <div class="settings-items-wrap">
          <div class="settings-items-header">
            <h4>Your lost items</h4>
            <%= image_tag 'simple_arrow_green.svg', class: 'settings-arrow' %>
          </div>
          <div class="settings-item-content">
            <% current_user.items.lost.each do |item| %>
              <div class="settings-item-details">
                <p><%= link_to item.title, item_path(item) %></p>
                <div class="settings-icon-wrap">
                  <%= link_to item_edit_lost_path(item) do %>
                 <i class="fas fa-pencil-alt"></i>
                 <% end %>
                 <div class="settings-icon-space"></div>
                  <%= link_to item_path(item),
                    method: :delete,
                    data: { confirm: "Are you sure?" } do %>
                    <i class="far fa-trash-alt"></i>
                  <% end %>
                </div>

              </div>
            <% end %>
          </div>
        </div>

      <% end %>

      <% if current_user.items.found %>

        <div class="settings-items-wrap">
          <div class="settings-items-header">
            <h4>Your found items</h4>
            <%= image_tag 'simple_arrow_green.svg', class: 'settings-arrow-found' %>
          </div>
          <div class="settings-item-content-found">
            <% current_user.items.found.each do |item| %>
              <div class="settings-item-details">
                <p><%= link_to item.title, item_path(item) %></p>
                <div class="settings-icon-wrap">
                <%= link_to item_edit_found_path(item) do %>
                 <i class="fas fa-pencil-alt"></i>
                 <% end %>
                 <div class="settings-icon-space"></div>
                <%= link_to item_path(item),
                  method: :delete,
                  data: { confirm: "Are you sure?" } do %>
                  <i class="far fa-trash-alt"></i>
                <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>

      <% end %>

      <!-- Display user reviews -->

      <% if current_user.reviews_as_reviewed %>

        <div class="settings-items-wrap">
          <div class="settings-items-header">
            <h4>Your reviews</h4>
            <%= image_tag 'simple_arrow_green.svg', class: 'settings-arrow-reviews' %>
          </div>
          <div class="settings-item-content-reviews">
            <% current_user.reviews_as_reviewed.each do |r| %>
              <div class="settings-review-wrap">
                <%= render 'reviews/rating_settings', user_rating: r.rating %>
                <div class="settings-review-content">
                  <%= r.content %>
                </div>
                <div class="settings-review-author">
                  <%= link_to (User.find(r.reviewer_id).first_name), user_path(r.reviewer.id) %>
                </div>
              </div>
            <% end  %>
           </div>
        </div>
      <% end %>

      <!-- Sign out -->

      <div class="settings-sign-out">
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      </div>

    </div>

  <!-- If user is not signed in -->

  <% else %>

  <div class="settings-sign-in">
    <%= link_to 'Sign in', new_user_session_path, class: 'button-green' %>
  </div>

  <% end %>


</div>