config/routes.rb
Rails.application.routes.draw do
  root to: 'items#home'
  get 'items/map', to: 'items#map', as: :map
  get 'items/search', to: 'items#search', as: :search
  get 'items/presentation', to: 'items#presentation', as: :presentation

  mount ActionCable.server, at: '/cable'

  resources :items, except: :home do
    get 'edit_lost', to: 'items#edit_lost', as: :edit_lost
    get 'edit_found', to: 'items#edit_found', as: :edit_found
    member do
      patch :solved
    end
    collection do
      get 'lost'
      get 'found'
      get 'new_lost'
      get 'new_found'
    end
    resources :conversations, only: [:create, :new]
  end

  resources :conversations, only: [:index, :show, :destroy] do
    resources :messages, only: [:index, :new, :create]
  end

  devise_for :users
   resources :users, only: [:show] do
    resources :reviews, only: [:new, :create, :index]
    end
    resources :reviews, only: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  enum state: [:lost, :found, :solved]

  CATEGORIES = [
    'Animal/Pet',
    'Art',
    'Electronics',
    'Accessories',
    'Clothes',
    'Furnitures',
    'Sports',
    'Transportation',
    'Credit Card',
    'Phone',
    'Keys',
    'Wallet',
    'Other'
  ]

  belongs_to :user
  has_many :conversations, dependent: :destroy
  validates :category, inclusion: { in: CATEGORIES }
  geocoded_by :address
  before_validation :geocode, if: :will_save_change_to_address?
  validate :address_is_geocoded
  def address_is_geocoded
    return if longitude && latitude
    errors.add(:address, 'could not map this address correctly!')
  end

  include AlgoliaSearch

  algoliasearch  do
    attribute :title, :address, :category, :state, :created_at

    attributesForFaceting [:state]



    geoloc :latitude, :longitude

      # ip = "193.214.55.86"

      # client = Algolia::Client.new(
      #   application_id: ENV['ALGOLIA_APP_ID'],
      #   api_key: ENV['ALGOLIA_SEARCH_KEY']
      # )

      # client.set_extra_header 'X-Forwarded-For', ip

      # index = client.init_index 'index_name'


  end

  # include PgSearch::Model
  # pg_search_scope :global_search,
  #   against: [ :title, :description, :category, :address, :created_at, :user_id ],
  #   using: {
  #     tsearch: { prefix: true } # <-- now `superman batm` will return something!
  #   }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:home, :index, :show, :map, :lost, :found]

  before_action :cached_location
  before_action :set_location, only: [:index, :found, :lost, :home]

  def cached_location
    ips = Geocoder.search(request.ip)

    if (ips.try(:first).try(:coordinates).any?)
      cookies[:cached_location] = ips.first.coordinates.join(',')
    end

    @coords = cookies[:cached_location]
    if @coords.blank?
      @coords = "59.8983942, 10.773181"
    end
  end

  def set_location
    @location = @coords.split(',').map(&:to_f)
  end

  def order_items
    return unless @items.present?

    @items = @items.sort_by { |item| item.distance_from(@location) }
  end

  def map
    items = Item.where.not(state: 'solved').geocoded
    set_map(items);
  end

  def presentation
  end

  def search
  end

  def home
    @items = Item.all
  end

  def index
    if search_terms
      @coords = "#{params[:latitude]}, #{params[:longitude]}" if params[:latitude].present?
      items = Item.where.not(state: 'solved').search(search_terms, {
        aroundLatLng: @coords,
        aroundRadius: @radius,
        hitsPerPage: 100
      })
      @items = date_filter(items)
      order_items
    else
      @items = Item.where.not(state: 'solved').all
      order_items
    end
  end

  def lost
    @items = Item.lost.where.not(state: 'solved')
    order_items
  end

  def found
    @items = Item.found.where.not(state: 'solved')
    order_items
    render :index
  end

  def new_found
    @item = Item.new
  end

  def new_lost
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])

    set_map(@item);
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    @item.user = current_user
    if @item.save
      flash[:notice] = "Added a new item!"
      redirect_to @item
    else
      if @item.found?
        render :new_found
      end
    end
  end

  def edit
  end

  def edit_found
    @item = Item.find(params[:item_id])
  end

  def edit_lost
    @item = Item.find(params[:item_id])
  end

  def update
    if @item.update(item_params)
      flash[:notice] = "You've updated your item!"
      redirect_to @item
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to root_path
  end

  def solved
    @item = Item.find(params[:id])
    @item.state = 2
    if @item.save!
      flash[:notice] = "Item has been marked as solved!"
      redirect_to @item
    else render :show
    end
  end


  private

  def search_terms
    if params[:radius]
      @radius = params[:radius].to_i*1000
    end
    search_item = params[:query]
    [
      search_item[:title],
      search_item[:category],
      search_item[:state]
    ].compact
  end

  def date_filter(items)
    search_item = params[:query]

    if !search_item[:start_date].blank? && !search_item[:stop_date].blank?
      items.select { |item|
        item.created_at >  search_item[:start_date].to_date && item.created_at <  search_item[:stop_date].to_date
      }
    elsif !search_item[:start_date].blank? && search_item[:stop_date].blank?
      items.select { |item|
        item.created_at >  search_item[:start_date].to_date
      }
    elsif search_item[:start_date].blank? && !search_item[:stop_date].blank?
      items.select { |item|
        item.created_at <  search_item[:stop_date].to_date
      }
    else
      items
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :state, :description, :category, :address, :reward, :photo)
  end

  def set_map(items)
    # Always convert items to array because if can be one item only!
    @markers = Array(items).map do |item|
      if item.state == 'lost'
        pointer = 'pointer_black.svg'
      else
        pointer = 'pointer_white.svg'
      end

      {
        lat: item.latitude,
        lng: item.longitude,
        infoWindow: render_to_string(partial: "map_info_window", locals: { item: item }),
        image_url: helpers.asset_url(pointer)
      }
    end
  end
end

app/views/items/_items_list.html.erb
<h2><span class="green counter"><%= @items.count %></span> results</h2>

<% if @items.count == 0 %>
  <div class="sorry-message"><h6>Sorry, no result matches your search.</h6></div>
  <button class="button-green">Please try again</button>
<% end %>
<div class="show-card-wrap">
  <%= render 'shared/show_card', items: @items, location: @location %>
</div>

app/views/items/_map_info_window.html.erb
<% if item.state == "lost" %>
  <div class="map-popup-black">
      <%= image_tag "pointer_black.svg" %>
    <div class="map-title">
      <h6><%= link_to item.title, item, class: "text-decoration-none" %></h6>
      <p><%= item.category %></p>
      <h6 class="reward">Reward: <%= item.reward %> kr </h6>
    </div >
  </div>
<% else %>
  <div class="map-popup-white">
    <%= image_tag "pointer_white.svg" %>
    <div class="map-title">
      <h6><%= link_to item.title, item, class: "text-decoration-none" %></h6>
      <p><%= item.category %></p>
      <!-- <h6 class="reward">Reward: <%= item.reward %> kr </h6> -->
      <h6 class="time-in-words"> <%= distance_of_time_in_words(item.created_at, Time.now) %> </h6>
    </div >
  </div>
<% end %>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit_found.html.erb
<div class="new-item-page-background">

</div>

 <div class="menu-title">
    <h2>Edit found item</h2>
  </div>

<div class="new-found-background-green">

</div>

<div class="new-found-background-white">
  <div class="new-item-form">
    <%= simple_form_for @item do |f| %>
      <%= f.input :title, :input_html => { placeholder: 'What have you found?', autocomplete: 'off'} %>
      <div class="search-dropdown">
        <div class="search-dropdown-results lost-dropdown drop-down-hidden">
        </div>
      </div>
      <%= f.input :description, :input_html => {:rows => 3, placeholder: 'Describe the item you have found', autocomplete: 'off'} %>
      <%= f.input :category, collection: Item::CATEGORIES, prompt: 'Select a category', :input_html => { placeholder: 'Please choose category' } %>
      <%= f.input :address, :input_html => { placeholder: 'Where did you find it?', autocomplete: 'off' } %>
      <div class="button-wrap">
      <%= f.button :submit, class:"button-green" %>
      <div class="button-space"></div>
      <%= link_to "Found Items", found_items_path, class:"button-dark"  %>
      </div>
    <% end %>

  </div>
</div>

app/views/items/home.html.erb
<div class="home-page-wrap">

  <div class="home-content-wrap">

    <div class="home-loaction-info">
      <%= image_tag 'map_green.svg', class: 'home-map-marker' %>
        <h3><%= Geocoder.search(@location).first.city %>, <%= Geocoder.search(@location).first.country %></h3>
    </div>
    <h1><span class="counter green">3657</span> lost</h1>
    <h1><span class="counter green">2356</span> found</h1>
      <%= simple_form_for :query, html: { class: "home-form"}, url: items_path, method: 'get' do |f| %>
        <%= f.input :title, input_html: { placeholder: 'Search nearby...', autocomplete: 'off' }, label: false, id: "home-input" %>
        <%= f.button :submit, "", id: "home-search-button"%>
      <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="show-page-wrap">
  <div class="show-container-list">
    <%= render 'items_list' %>
  </div>
</div>

app/views/items/lost.html.erb
<div class="show-page-wrap-lost">
  <div class="show-container-list lost">
    <%= render 'items_list' %>
  </div>
</div>

app/views/items/map.html.erb
<div
  id="map"
  style="width: 100%;
  height: auto;
  position: fixed;
/*  height: calc(100vh - 60px);*/
  right:0;
  top:0;
  left: 0;
  bottom: 60px;
  "
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/items/new_found.html.erb
<div class="new-item-page-background">

</div>

 <div class="menu-title">
    <h2>New found item</h2>
  </div>

<div class="new-found-background-green">

</div>

<div class="new-found-background-white">
  <div class="new-item-form">
    <%= simple_form_for @item, :url => url_for(:action => 'create', :controller => 'items'), :method => 'post' do |f| %>
      <%= f.input :state, as: :hidden, input_html: { value: params[:state] } %>
      <%= f.input :title, :input_html => { placeholder: 'What have you found?', autocomplete: 'off'} %>
      <div class="search-dropdown">
        <div class="search-dropdown-results lost-dropdown">
        </div>
      </div>
      <%= f.input :description, :input_html => {:rows => 3, placeholder: 'Describe the item you have found', autocomplete: 'off'} %>
      <%= f.input :category, collection: Item::CATEGORIES, prompt: 'Select a category', :input_html => { placeholder: 'Please choose category' } %>
      <%= f.input :address, :input_html => { placeholder: 'Where did you find it?', required: true } %>
      <div class="button-wrap">
      <%= f.button :submit, class:"button-green-dark" %>
      <div class="button-space"></div>
      <%= link_to 'Back', :back, class: 'button-green-dark' %>
    <% end %>

  </div>
</div>

app/views/items/new_lost.html.erb
<div class="new-item-page-background">

</div>

<div class="menu-title">
  <h2>New lost item</h2>
</div>

<div class="new-found-background-green">

</div>

<div class="new-lost-background-dark">
  <div class="new-item-form-lost">
    <%= simple_form_for @item, :url => url_for(:action => 'create', :controller => 'items'), :method => 'post' do |f| %>
      <%= f.input :state, as: :hidden, input_html: { value: params[:state] } %>
      <%= f.input :title, :input_html => { placeholder: 'What have you lost?', autocomplete: 'off' } %>
      <div class="search-dropdown">
        <div class="search-dropdown-results found-dropdown">
        </div>
      </div>
      <%= f.input :description, :input_html => {:rows => 3, placeholder: 'Describe the item you have lost', autocomplete: 'off'} %>
      <%= f.input :category, collection: Item::CATEGORIES, prompt: 'Select a category', :input_html => { placeholder: 'Please choose category' } %>
      <%= f.input :address, :input_html => { placeholder: 'Where did you lose it?', required: true } %>
      <%= f.input :reward, :input_html => { placeholder: 'Do you want to give a finders fee?', autocomplete: 'off' } %>
      <div class="button-wrap">
      <%= f.button :submit, class:"button-green" %>
            <div class="button-space"></div>
      <%= link_to 'Back', :back, class: 'button-green' %>
    <% end %>

  </div>
</div>

app/views/items/presentation.html.erb
<div class="sign-in-page-wrap">

  <div class="logo-wrap">
    <div class="logo-big">
      <div class="logo-small"></div>
    </div>
  </div>

  <div class="logo-title">
    <%= link_to 'lost & found', root_path %>
  </div>

  <div class="tag-line">Join our community and find your lost belongings!</div>


</div>

app/views/items/search.html.erb
<div class="container" id="search-page-form">
  <div class="row justify-content-center">
    <div class="search-form col-sm-12 col-md-6">
        <%= simple_form_for :query, :url => url_for(:action => 'index', :controller => 'items'), :method => 'get' do |f| %>
          <%= f.input :title, :input_html => { placeholder: 'What you are looking for?', autocomplete: 'off' }, required: false %>
          <%= f.input :category, collection: Item::CATEGORIES, prompt: 'Select category', :input_html => { placeholder: 'Please choose category'}, required: false %>
          <%= f.input :state, collection: ['found', 'lost'], selected: 1, :input_html => { placeholder: ''}, required: false, label: 'Lost or Found?' %>
          <%#= f.input :rasius, as: :range %>

          <div class="search-dates">
            <%= f.input :start_date, as: :date, html5: true, class: "date", label: "from:", required: false %>
            <%= f.input :stop_date, as: :date, html5: true, class: "date", label: "to:", required: false %>
          </div>
          <div class="slidecontainer">
            <label for="range">Radius</label>
            <input type="range" min="1" max="30" value="5" class="slider" id="myRange" name="radius">
            <div class="d-flex justify-content-between">
              <h5></h5>
              <div>
                <h5 class="text-muted"><output id="demo">30</output> km</h5>
              </div>
            </div>
          </div>
          <%= f.input :address, :input_html => { placeholder: 'Please enter your address ...', autocomplete: 'off' }, required: false, id: "flat_address" %>
          <div class="button-wrap pt-2">
            <%= f.button :submit, 'Search', class:"button-green-dark"%>
          </div>
            <input type="hidden" id="latitude" name="latitude" value="">
            <input type="hidden" id="longitude" name="longitude" value="">
        <% end %>
    </div>
  </div>

app/views/items/show.html.erb
<% content_for :meta_title, "#{@item.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @item.description %>

<div class="<%= @item.lost? ? 'show-page-wrap-lost' : 'show-page-wrap' %>" id="map-show">
  <div
    id="map"
    style="width: 100%;
    height: 50vh;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>

  <div class="show-container <%= @item.lost? ? 'lost' : '' %>">
    <h3><%= @item.title %></h3>
    <div class="show-item-details">
      <div class="item-details-user">
        <i class="fas fa-user"></i>
        <%= link_to @item.user.first_name, user_path(@item.user) %>
      </div>
      <div class="<%= @item.lost? ? 'item-details-time-lost' : 'item-details-time' %>">
        <%= distance_of_time_in_words(@item.created_at, Time.now) %> ago
      </div>
    </div>

    <% if @item.reward && @item.lost? %>
      <div class="show-finders-fee">
        <i class="fas fa-coins"></i>
        <%= @item.reward %> kr finders fee
      </div>
    <% end %>

    <div class="show-item-description">
      <%= @item.description %>
    </div>

    <% if current_user %>
    <div class="button-wrap">
      <% if current_user.conversation_for(@item).present? %>
        <%= link_to 'Send message', current_user.conversation_for(@item), class: @item.lost? ? 'button-green-lost' : 'button-green-dark' %>
      <% else %>
        <%= link_to 'Send message', new_item_conversation_path(@item), class: @item.lost? ? 'button-green-lost' : 'button-green-dark' %>
      <% end %>
      <div class="button-space"></div>
      <% if current_user == @item.user && (@item.lost? || @item.found?) %>
      <%= link_to 'Mark as solved', solved_item_path(@item), method: :patch, class: 'button-green-dark' %>
      <% else %>
      <%= link_to 'Write Review', user_path(@item.user), class: @item.lost? ? 'button-green-lost' : 'button-green-dark' %>
      <% end  %>
    </div>
    <% else %>
    <p><i>Please sign in to send a message</i></p>
    <% end %>

    <div id="show-back-button">
      <%= link_to "Back to list", @item.lost? ? lost_items_path : found_items_path %>
    </div>

  </div>
</div>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>