config/routes.rb
Rails.application.routes.draw do
  root to: 'items#home'
  get 'items/map', to: 'items#map', as: :map
  get 'items/search', to: 'items#search', as: :search
  get 'items/presentation', to: 'items#presentation', as: :presentation

  mount ActionCable.server, at: '/cable'

  resources :items, except: :home do
    get 'edit_lost', to: 'items#edit_lost', as: :edit_lost
    get 'edit_found', to: 'items#edit_found', as: :edit_found
    member do
      patch :solved
    end
    collection do
      get 'lost'
      get 'found'
      get 'new_lost'
      get 'new_found'
    end
    resources :conversations, only: [:create, :new]
  end

  resources :conversations, only: [:index, :show, :destroy] do
    resources :messages, only: [:index, :new, :create]
  end

  devise_for :users
   resources :users, only: [:show] do
    resources :reviews, only: [:new, :create, :index]
    end
    resources :reviews, only: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @reviews = @user.reviews_as_reviewed
  end

  def show
    @review = Review.find(params[:id])
    @reviewer = User.find(@review.reviewer_id)
    @reviewed = User.find(@review.reviewed_id)
  end

  def new
    @review = Review.new
    @user = User.find(params[:user_id])
  end

  def create
    @review = Review.new(review_params)
    @user = User.find(params[:user_id])
    @review.reviewed_id = @user.id
    @review.reviewer_id = current_user.id
    @review.save
     if @review.save
      flash[:notice] = "Added a new review!"
      redirect_to user_path(@user)
    else render :new
    end
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end

  private

  def review_params
  params.require(:review).permit(:content, :rating)
  end

end

app/views/reviews/_form.html.erb
<%= simple_form_for [user, review] do |f| %>
  <%= f.input :content, :input_html => {:rows => 3, placeholder: 'Write your feedback...'} %>
  <%= f.input :rating, collection: 0..5, prompt: 'Choose number of stars', :input_html => { placeholder: 'Please choose category' } %>
  <%= f.button :submit, class: 'button-dark' %>
<% end %>

app/views/reviews/_rating.html.erb
<div class="user_average_rating">
  <% if user_rating == 0 %>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
  <% elsif user_rating == 0.5 %>
    <i class="fas fa-star-half star-green"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
  <% elsif user_rating == 1 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
  <% elsif user_rating == 1.5 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star-half star-green"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
  <% elsif user_rating == 2 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
  <% elsif user_rating == 2.5 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star-half star-green"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
  <% elsif user_rating == 3 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-gray"></i>
    <i class="fas fa-star star-gray"></i>
  <% elsif user_rating == 3.5 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star-half star-green"></i>
    <i class="fas fa-star star-gray"></i>
  <% elsif user_rating == 4 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-gray"></i>
  <% elsif user_rating == 4.5 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star-half star-green"></i>
    <i class="fas fa-star star-gray"></i>
  <% elsif user_rating == 5 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
  <% end %>
</div>

app/views/reviews/_rating_settings.html.erb
<div class="user_average_rating">
  <% if user_rating == 0 %>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
  <% elsif user_rating == 0.5 %>
    <i class="fas fa-star-half star-green"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
  <% elsif user_rating == 1 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
  <% elsif user_rating == 1.5 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star-half star-green"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
  <% elsif user_rating == 2 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
  <% elsif user_rating == 2.5 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star-half star-green"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
  <% elsif user_rating == 3 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-white"></i>
    <i class="fas fa-star star-white"></i>
  <% elsif user_rating == 3.5 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star-half star-green"></i>
    <i class="fas fa-star star-white"></i>
  <% elsif user_rating == 4 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-white"></i>
  <% elsif user_rating == 4.5 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star-half star-green"></i>
    <i class="fas fa-star star-white"></i>
  <% elsif user_rating == 5 %>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
    <i class="fas fa-star star-green"></i>
  <% end %>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/delete.html.erb
<h1>Reviews#delete</h1>
<p>Find me in app/views/reviews/delete.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

<%= simple_form_for @review do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :rating %>
  <%= f.input :age, collection: 0..5 %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/index.html.erb
<div class="show-page-wrap">

  <div class="top-menu-wrap">
    <div class="menu-item">
        <%= image_tag 'simple_arrow_white.svg', class: 'settings-back' %>
    </div>
    <div class="menu-item">
        <%= link_to image_tag("logo_green.svg", class: "menu-logo"), root_path %>
    </div>
    <div class="menu-item">
      <%= image_tag 'chat_white.svg', class: 'menu-chat' %>
    </div>
  </div>

  <% if user_signed_in? %>

    <div class="settings-wrap">

      <!-- profile picture and name -->

      <div class="settings-user-wrap">
        <%= image_tag 'placeholder.jpg', class: 'settings-placeholder' %>
        <div class="settings-user-details">
          <h4><%= current_user.first_name %></h4>
          <h4> <%= current_user.last_name %></h4>
          <p>Add profile picture</p>
        </div>
      </div>

      <!-- Account information -->

      <div class="settings-account">
        <div class="account-items account-header">
          Account settings
          <%= link_to 'Edit profile', '#', class: 'settings-links' %>
        </div>
        <div class="account-items">
          <p>Email</p>
          <p><%= current_user.email %></p>
        </div>
        <div class="account-items">
          <p>Phone number</p>
          <p><%= current_user.phone_number %></p>
        </div>
      </div>

      <!-- Display lost and found items -->

      <% if current_user.items.lost %>

        <div class="settings-items-wrap">
          <div class="settings-items-header">
            <h4>Your lost items</h4>
            <%= image_tag 'simple_arrow_green.svg', class: 'settings-arrow' %>
          </div>
          <div class="settings-item-content">
            <% current_user.items.lost.each do |item| %>
              <div class="settings-item-details">
                <p><%= link_to item.title, item_path(item) %></p>
                <%= link_to item_path(item),
                  method: :delete,
                  data: { confirm: "Are you sure?" } do %>
                  <i class="far fa-trash-alt"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>

      <% end %>

      <% if current_user.items.found %>

        <div class="settings-items-wrap">
          <div class="settings-items-header">
            <h4>Your found items</h4>
            <%= image_tag 'simple_arrow_green.svg', class: 'settings-arrow-found' %>
          </div>
          <div class="settings-item-content-found">
            <% current_user.items.found.each do |item| %>
              <div class="settings-item-details">
                <p><%= link_to item.title, item_path(item) %></p>
                <%= link_to item_path(item),
                  method: :delete,
                  data: { confirm: "Are you sure?" } do %>
                  <i class="far fa-trash-alt"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>

      <% end %>

      <div class="settings-sign-out">
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </div>

    </div>

  <% else %>

  <div class="settings-sign-in">
    <%= link_to 'Sign in', new_user_session_path, class: 'button-green' %>
  </div>

  <% end %>


</div>


<div class="show-page-wrap">

  <div class="show-container">

    <h1><%= @user.first_name %></h1>

    <% if @reviews %>
    <ul>
      <% @reviews.each do |r| %>
      <li>
        <p>Review:<%= r.content %></p>
        <p>Rating:  <%= r.rating %> </p>
        <p>Author: <%= link_to (User.find(r.reviewer_id).first_name), user_path(r.reviewer.id) %></p>
      </li>
    <% end  %>
    </ul>
    <% end %>



    <%= link_to 'Create Review', new_user_review_path(@user)  %>

  </div>
</div>

app/views/reviews/new.html.erb
<%= render 'form', user: @user, review: @review %>

app/views/reviews/show.html.erb
<div class="show-page-wrap">

  <div class="show-container">
  <div>
  <p> Review for: <%= @reviewed.first_name %> </p>
  <p> Content: <%= @review.content %> </p>
  <p> Author: <%= @reviewer.first_name %> </p>
  <p> Rating: <%= @review.rating %></p>
  </div>

  <%= link_to "View user ratings", user_reviews_path(@reviewed) %>
  </div>
</div>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>